<a href="https://colab.research.google.com/github/vinivijayan1/Google-co-lab-pages/blob/main/Copy_of_Day_4_Breast_Cancer_Prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/content/breast_cancer.csv")
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
data['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [ ]:
data['new_diagnosis'] = data['diagnosis'].map({"M":1,"B":0})
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0  ...           184.60      2019.0            0.1622             0.6656   
1  ...           158.80      1956.0            0.1238             0.1866   
2  ...           152.50      1709.0            0.1444             0.4245   
3  ...            98.87       567.7            0.2098             0.8663   
4  ...           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  new_diagnosis  
0                  0.11890          NaN              1  
1                  0.08902          NaN              1  
2                  0.08758          NaN              1  
3                  0.17300          NaN              1  
4                  0.07678          NaN              1  

[5 rows x 34 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['new_diagnosis'] = le.fit_transform(data['diagnosis'])
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0  ...           184.60      2019.0            0.1622             0.6656   
1  ...           158.80      1956.0            0.1238             0.1866   
2  ...           152.50      1709.0            0.1444             0.4245   
3  ...            98.87       567.7            0.2098             0.8663   
4  ...           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  new_diagnosis  
0                  0.11890          NaN              1  
1                  0.08902          NaN              1  
2                  0.08758          NaN              1  
3                  0.17300          NaN              1  
4                  0.07678          NaN              1  

[5 rows x 34 columns]

In [ ]:
data.head(1)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  842302         M        17.99         10.38           122.8     1001.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.1184            0.2776          0.3001               0.1471   

   ...  perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0  ...            184.6      2019.0            0.1622             0.6656   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   

   fractal_dimension_worst  Unnamed: 32  new_diagnosis  
0                   0.1189          NaN              1  

[1 rows x 34 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
### divide the data into features and targets
x = data.iloc[:,2:32]
y = data.iloc[:,33]

In [ ]:
### Split the data into train and testing samples
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.80,random_state=1)

In [ ]:
len(xtrain)

455

In [ ]:
len(xtest)

114

In [ ]:
data['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [ ]:
import numpy as np
np.unique(ytrain,return_counts=True)

(array([0, 1]), array([285, 170]))

In [ ]:
import keras as tf

In [ ]:
model = tf.models.Sequential()  ## blank model
## add the layers
model.add(tf.layers.Dense(16,input_dim=30,activation='relu'))  ## input and one hidden layer
model.add(tf.layers.Dense(32,activation='relu'))  ## second hidden layer
model.add(tf.layers.Dense(2,activation='softmax'))
## Compile the model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
### binary_crossentropy | sparse_categorical_crossentropy

In [ ]:
### Training the model
model.fit(xtrain,ytrain,epochs=500)

Epoch 1/500
15/15 [==============================] - 1s 2ms/step - loss: 3.3488 - accuracy: 0.6791
Epoch 2/500
15/15 [==============================] - 0s 2ms/step - loss: 1.2809 - accuracy: 0.8615
Epoch 3/500
15/15 [==============================] - 0s 2ms/step - loss: 0.7988 - accuracy: 0.8637
Epoch 4/500
15/15 [==============================] - 0s 2ms/step - loss: 0.5742 - accuracy: 0.8769
Epoch 5/500
15/15 [==============================] - 0s 2ms/step - loss: 0.4024 - accuracy: 0.9033
Epoch 6/500
15/15 [==============================] - 0s 2ms/step - loss: 0.3083 - accuracy: 0.8989
Epoch 7/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2144 - accuracy: 0.9253
Epoch 8/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2247 - accuracy: 0.9231
Epoch 9/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2093 - accuracy: 0.9209
Epoch 10/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2457 - accuracy: 0.9187
Epoch 11/

In [ ]:
### Testing / Predictions
ypred = model.predict(xtest)
ypred = ypred.round()
ypred

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [ ]:
ytest

421    0
47     1
292    0
186    1
414    1
      ..
172    1
3      1
68     0
448    0
442    0
Name: new_diagnosis, Length: 114, dtype: int64

In [ ]:
model.evaluate(xtest,ytest)

4/4 [==============================] - 0s 3ms/step - loss: 0.1783 - accuracy: 0.9298


[0.17831921577453613, 0.9298245906829834]

In [ ]:
### Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypred)
cm

ValueError: ignored

In [ ]:
### Testing / Predictions
ypred = model.predict(xtest)
ypred

array([[9.60961521e-01, 3.90384533e-02],
       [6.61624968e-02, 9.33837473e-01],
       [9.98417020e-01, 1.58293883e-03],
       [3.64006992e-05, 9.99963641e-01],
       [2.54900724e-01, 7.45099306e-01],
       [1.88963277e-05, 9.99981046e-01],
       [8.11252184e-03, 9.91887510e-01],
       [1.91858318e-02, 9.80814099e-01],
       [9.99921322e-01, 7.86701057e-05],
       [9.99305964e-01, 6.94000453e-04],
       [9.99680996e-01, 3.19037790e-04],
       [3.36082667e-01, 6.63917303e-01],
       [6.35729671e-01, 3.64270329e-01],
       [9.98795748e-01, 1.20419287e-03],
       [9.87629652e-01, 1.23703377e-02],
       [9.86540973e-01, 1.34590864e-02],
       [9.99766171e-01, 2.33794955e-04],
       [9.99357998e-01, 6.41969265e-04],
       [9.99843836e-01, 1.56084861e-04],
       [2.25555155e-07, 9.99999762e-01],
       [9.98321593e-01, 1.67833176e-03],
       [9.98083711e-01, 1.91633427e-03],
       [7.71928998e-03, 9.92280662e-01],
       [9.99525547e-01, 4.74456145e-04],
       [1.570201

In [ ]:
ypred[1].argmax()


1

In [ ]:
new_ypred = []
for i in range(len(ypred)):
  new_ypred.append(ypred[i].argmax())

In [ ]:
ypred

array([[9.60961521e-01, 3.90384533e-02],
       [6.61624968e-02, 9.33837473e-01],
       [9.98417020e-01, 1.58293883e-03],
       [3.64006992e-05, 9.99963641e-01],
       [2.54900724e-01, 7.45099306e-01],
       [1.88963277e-05, 9.99981046e-01],
       [8.11252184e-03, 9.91887510e-01],
       [1.91858318e-02, 9.80814099e-01],
       [9.99921322e-01, 7.86701057e-05],
       [9.99305964e-01, 6.94000453e-04],
       [9.99680996e-01, 3.19037790e-04],
       [3.36082667e-01, 6.63917303e-01],
       [6.35729671e-01, 3.64270329e-01],
       [9.98795748e-01, 1.20419287e-03],
       [9.87629652e-01, 1.23703377e-02],
       [9.86540973e-01, 1.34590864e-02],
       [9.99766171e-01, 2.33794955e-04],
       [9.99357998e-01, 6.41969265e-04],
       [9.99843836e-01, 1.56084861e-04],
       [2.25555155e-07, 9.99999762e-01],
       [9.98321593e-01, 1.67833176e-03],
       [9.98083711e-01, 1.91633427e-03],
       [7.71928998e-03, 9.92280662e-01],
       [9.99525547e-01, 4.74456145e-04],
       [1.570201

In [ ]:
model.evaluate(xtest,ytest)


4/4 [==============================] - 0s 3ms/step - loss: 0.1783 - accuracy: 0.9298


[0.17831921577453613, 0.9298245906829834]

In [ ]:
### Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,new_ypred)
cm

array([[71,  1],
       [ 7, 35]])

In [ ]:
### Confusion Matrix
from sklearn.metrics import accuracy_score
a = accuracy_score(ytest,new_ypred)
a

0.9298245614035088