<a href="https://colab.research.google.com/github/vinivijayan1/Google-co-lab-pages/blob/main/Day_4_Breast_Cancer_Prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/content/breast_cancer.csv")
data.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
data['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [ ]:
data['new_diagnosis'] = data['diagnosis'].map({"M":1,"B":0})
data.head()

id diagnosis  ...  Unnamed: 32  new_diagnosis
0    842302         M  ...          NaN              1
1    842517         M  ...          NaN              1
2  84300903         M  ...          NaN              1
3  84348301         M  ...          NaN              1
4  84358402         M  ...          NaN              1

[5 rows x 34 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['new_diagnosis'] = le.fit_transform(data['diagnosis'])
data.head()

id diagnosis  ...  Unnamed: 32  new_diagnosis
0    842302         M  ...          NaN              1
1    842517         M  ...          NaN              1
2  84300903         M  ...          NaN              1
3  84348301         M  ...          NaN              1
4  84358402         M  ...          NaN              1

[5 rows x 34 columns]

In [ ]:
data.head(1)

id diagnosis  ...  Unnamed: 32  new_diagnosis
0  842302         M  ...          NaN              1

[1 rows x 34 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
### divide the data into features and targets
x = data.iloc[:,2:32]
y = data.iloc[:,33]

In [ ]:
### Split the data into train and testing samples
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.80,random_state=1)

In [ ]:
len(xtrain)

455

In [ ]:
len(xtest)

114

In [ ]:
data['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [ ]:
import numpy as np
np.unique(ytrain,return_counts=True)

(array([0, 1]), array([285, 170]))

In [ ]:
import keras as tf

In [ ]:
model = tf.models.Sequential()  ## blank model
## add the layers
model.add(tf.layers.Dense(16,input_dim=30,activation='relu'))  ## input and one hidden layer
model.add(tf.layers.Dense(32,activation='relu'))  ## second hidden layer
model.add(tf.layers.Dense(2,activation='softmax'))
## Compile the model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
### binary_crossentropy | sparse_categorical_crossentropy

In [ ]:
### Training the model
model.fit(xtrain,ytrain,epochs=500)

Epoch 1/500
15/15 [==============================] - 0s 2ms/step - loss: 17.8572 - accuracy: 0.4816
Epoch 2/500
15/15 [==============================] - 0s 1ms/step - loss: 2.2780 - accuracy: 0.6086
Epoch 3/500
15/15 [==============================] - 0s 1ms/step - loss: 0.5487 - accuracy: 0.8775
Epoch 4/500
15/15 [==============================] - 0s 2ms/step - loss: 0.5252 - accuracy: 0.9088
Epoch 5/500
15/15 [==============================] - 0s 2ms/step - loss: 0.4363 - accuracy: 0.8999
Epoch 6/500
15/15 [==============================] - 0s 1ms/step - loss: 0.4888 - accuracy: 0.9071
Epoch 7/500
15/15 [==============================] - 0s 1ms/step - loss: 0.3823 - accuracy: 0.9043
Epoch 8/500
15/15 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.9293
Epoch 9/500
15/15 [==============================] - 0s 2ms/step - loss: 0.3336 - accuracy: 0.9293
Epoch 10/500
15/15 [==============================] - 0s 3ms/step - loss: 0.3676 - accuracy: 0.9079
Epoch 11

In [ ]:
### Testing / Predictions
ypred = model.predict(xtest)
ypred

In [ ]:
ypred[1].argmax()

1

In [ ]:
new_ypred = []
for i in range(len(ypred)):
  new_ypred.append(ypred[i].argmax())

In [ ]:
ytest.shape

(114,)

In [ ]:
import numpy as np
new_ypred = np.array(new_ypred)
new_ypred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0])

In [ ]:
ypred

array([[5.99055529e-01, 4.00944531e-01],
       [7.82106945e-04, 9.99217868e-01],
       [9.81241822e-01, 1.87582057e-02],
       [2.80080403e-09, 1.00000000e+00],
       [1.28364284e-03, 9.98716354e-01],
       [4.57168348e-09, 1.00000000e+00],
       [5.47129078e-11, 1.00000000e+00],
       [9.48873912e-06, 9.99990463e-01],
       [9.95860040e-01, 4.14001103e-03],
       [9.58168030e-01, 4.18319441e-02],
       [9.97444749e-01, 2.55525485e-03],
       [1.70951150e-02, 9.82904911e-01],
       [3.78324254e-03, 9.96216714e-01],
       [9.77124751e-01, 2.28752550e-02],
       [2.67447770e-01, 7.32552230e-01],
       [7.73990333e-01, 2.26009622e-01],
       [9.96513546e-01, 3.48645123e-03],
       [9.89276528e-01, 1.07235024e-02],
       [9.79592264e-01, 2.04077139e-02],
       [1.39790333e-13, 1.00000000e+00],
       [9.79357481e-01, 2.06425376e-02],
       [9.86795008e-01, 1.32049648e-02],
       [4.60281626e-07, 9.99999523e-01],
       [9.84982014e-01, 1.50179639e-02],
       [1.486541

In [ ]:
model.evaluate(xtest,ytest)

4/4 [==============================] - 0s 2ms/step - loss: 0.2098 - accuracy: 0.9211


[0.2098167985677719, 0.9210526347160339]

In [ ]:
### Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,new_ypred)
cm

array([[65,  7],
       [ 2, 40]])

In [ ]:
### Confusion Matrix
from sklearn.metrics import accuracy_score
a = accuracy_score(ytest,new_ypred)
a

0.9210526315789473

In [ ]:
### Check new Sample
inputs = [17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890]
#len(inputs)
model.predict([inputs]).argmax()

1

In [ ]:
model.save("breast_cancer.h5")

In [ ]:
import keras as tf
mymodel = tf.models.load_model("/content/breast_cancer.h5")

In [ ]:
### Check new Sample
inputs = [17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890]
#len(inputs)
mymodel.predict([inputs]).argmax()

1